/**
 * Baseline Diagnostic Service - Phase 1
 * Handles baseline matrix diagnostic and remediation
 */

export interface BaselineEntry {
  ISO3: string;
  Country: string;
  Vector: string;
  factor_value: number;
  source_name: string;
  source_type: string;
  timestamp: string;
  fallback_type: string;
  configured_weight: number;
  applied_weight: number;
  weighted_contribution: number;
}

export class BaselineDiagnosticService {
  /**
   * Generate baseline matrix CSV for all countries
   */
  static async generateBaselineMatrix(): Promise<string> {
    // This would normally fetch from the actual CSI database
    // For now, we'll read the existing CSV file generated by David
    const response = await fetch('/baseline_matrix_full.csv');
    if (!response.ok) {
      throw new Error('Failed to load baseline matrix data');
    }
    return await response.text();
  }

  /**
   * Generate incomplete coverage report
   */
  static async generateIncompleteCoverage(): Promise<string> {
    const response = await fetch('/incomplete_coverage.csv');
    if (!response.ok) {
      throw new Error('Failed to load incomplete coverage data');
    }
    return await response.text();
  }

  /**
   * Generate completeness summary
   */
  static async generateCompletenessSummary(): Promise<string> {
    const response = await fetch('/completeness_summary.csv');
    if (!response.ok) {
      throw new Error('Failed to load completeness summary data');
    }
    return await response.text();
  }

  /**
   * Download CSV file
   */
  static downloadCSV(content: string, filename: string): void {
    const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    const url = URL.createObjectURL(blob);
    
    link.setAttribute('href', url);
    link.setAttribute('download', filename);
    link.style.visibility = 'hidden';
    
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    URL.revokeObjectURL(url);
  }

  /**
   * Generate and download all Phase 1 diagnostic files
   */
  static async downloadAllPhase1Files(): Promise<void> {
    try {
      const [baseline, incomplete, summary] = await Promise.all([
        this.generateBaselineMatrix(),
        this.generateIncompleteCoverage(),
        this.generateCompletenessSummary()
      ]);

      // Download files with slight delays to avoid browser blocking
      this.downloadCSV(baseline, 'baseline_matrix_full.csv');
      
      setTimeout(() => {
        this.downloadCSV(incomplete, 'incomplete_coverage.csv');
      }, 300);
      
      setTimeout(() => {
        this.downloadCSV(summary, 'completeness_summary.csv');
      }, 600);
    } catch (error) {
      console.error('Error downloading Phase 1 files:', error);
      throw error;
    }
  }
}