export const COMPANY_SPECIFIC_EXPOSURES: Record<string, CompanyExposure> = {
  'AAPL': {
    ticker: 'AAPL',
    companyName: 'AAPL Inc.',
    homeCountry: 'Other countries',
    sector: 'Technology',
    exposures: [
      { country: 'Other countries', percentage: 37.8, description: 'Revenue segment from 10-K' },
      { country: 'China (1)', percentage: 12.2, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 6.1, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 4.5, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 4.5, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 4.5, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Thailand', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Malaysia', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Indonesia', percentage: 1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-10-31',
    lastUpdated: '2025-12-10'
  },
  'GOOGL': {
    ticker: 'GOOGL',
    companyName: 'GOOGL Inc.',
    homeCountry: 'Revenues, excluding hedging effect',
    sector: 'Technology',
    exposures: [
      { country: 'Revenues, excluding hedging effect', percentage: 32.8, description: 'Revenue segment from 10-K' },
      { country: 'EMEA(1)', percentage: 27.7, description: 'Revenue segment from 10-K' },
      { country: 'APAC(1)', percentage: 15.9, description: 'Revenue segment from 10-K' },
      { country: 'Other Americas(1)', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'Other Americas', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Hedging gains (losses)', percentage: 0.7, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-05',
    lastUpdated: '2025-12-10'
  },
  'NVDA': {
    ticker: 'NVDA',
    companyName: 'NVDA Inc.',
    homeCountry: 'Singapore (1)',
    sector: 'Technology',
    exposures: [
      { country: 'Singapore (1)', percentage: 34.2, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 29.7, description: 'Revenue segment from 10-K' },
      { country: 'China (including Hong Kong)', percentage: 24.7, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 11.4, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-26',
    lastUpdated: '2025-12-10'
  },
  'META': {
    ticker: 'META',
    companyName: 'META Inc.',
    homeCountry: 'Asia-Pacific (2)',
    sector: 'Technology',
    exposures: [
      { country: 'Asia-Pacific (2)', percentage: 44.4, description: 'Revenue segment from 10-K' },
      { country: 'Europe (3)', percentage: 37.9, description: 'Revenue segment from 10-K' },
      { country: 'Rest of World (3)', percentage: 17.7, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-01-30',
    lastUpdated: '2025-12-10'
  },
  'JPM': {
    ticker: 'JPM',
    companyName: 'JPM Inc.',
    homeCountry: 'United States',
    sector: 'Financial Services',
    exposures: [
      { country: 'United States', percentage: 17.3, description: 'Revenue segment from 10-K' },
      { country: 'Canada', percentage: 16.3, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 16.3, description: 'Revenue segment from 10-K' },
      { country: 'Commercial Banking', percentage: 14.9, description: 'Revenue segment from 10-K' },
      { country: 'Middle Market Banking', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Commercial Real Estate Banking', percentage: 4.8, description: 'Revenue segment from 10-K' },
      { country: 'Latin America/Caribbean', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'Year ended December 31,(in billions, except where otherwise noted)', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Year ended December 31,(in millions)', percentage: 2.6, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'All other regions', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'As of or for the year ended December 31, (in millions, except where otherwise noted)', percentage: 0.1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-14',
    lastUpdated: '2025-12-10'
  },
  'JNJ': {
    ticker: 'JNJ',
    companyName: 'JNJ Inc.',
    homeCountry: 'Segment earnings before tax(1)',
    sector: 'Healthcare',
    exposures: [
      { country: 'Segment earnings before tax(1)', percentage: 47.9, description: 'Revenue segment from 10-K' },
      { country: 'Innovative Medicine', percentage: 40, description: 'Revenue segment from 10-K' },
      { country: 'MedTech', percentage: 7.9, description: 'Revenue segment from 10-K' },
      { country: '(Dollars in Millions)', percentage: 4.3, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-13',
    lastUpdated: '2025-12-10'
  },
  'PG': {
    ticker: 'PG',
    companyName: 'PG Inc.',
    homeCountry: 'Fabric & Home Care',
    sector: 'Consumer Defensive',
    exposures: [
      { country: 'Fabric & Home Care', percentage: 35.6, description: 'Revenue segment from 10-K' },
      { country: 'Baby, Feminine & Family Care', percentage: 23.8, description: 'Revenue segment from 10-K' },
      { country: 'Beauty', percentage: 17.8, description: 'Revenue segment from 10-K' },
      { country: 'Health Care', percentage: 13.9, description: 'Revenue segment from 10-K' },
      { country: 'Grooming', percentage: 7.9, description: 'Revenue segment from 10-K' },
      { country: 'Reportable Segments', percentage: 1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-08-04',
    lastUpdated: '2025-12-10'
  },
  'HD': {
    ticker: 'HD',
    companyName: 'HD Inc.',
    homeCountry: 'Primary segment net sales',
    sector: 'Consumer Cyclical',
    exposures: [
      { country: 'Primary segment net sales', percentage: 36.6, description: 'Revenue segment from 10-K' },
      { country: 'Décor', percentage: 6.6, description: 'Revenue segment from 10-K' },
      { country: 'Hardlines', percentage: 6.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 10. Employee Benefit Plans', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Note 11. Weighted Average Common Shares', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Note 12. Commitments and Contingencies', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Note 13. Acquisitions', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Note 9. Stock-Based Compensation', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 7. Stockholders' Equity', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 8. Fair Value Measurements', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 5. Debt and Derivative Instruments', percentage: 2.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 4. Goodwill and Intangible Assets', percentage: 2.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 3. Property and Leases', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 2. Segment Reporting and Net Sales', percentage: 2.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 1. Summary of Significant Accounting Policies', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Report of Independent Registered Public Accounting Firm', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Other net sales', percentage: 1.5, description: 'Revenue segment from 10-K' },
      { country: 'Power', percentage: 1.5, description: 'Revenue segment from 10-K' },
      { country: 'Building Materials', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'Plumbing', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'Lumber', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Paint', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Indoor Garden', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Outdoor Garden', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Hardware', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Flooring', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Millwork', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Electrical', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Kitchen & Blinds', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Bath', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Storage & Organization', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Lighting', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'in millions', percentage: 0.3, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-03-21',
    lastUpdated: '2025-12-10'
  },
  'BAC': {
    ticker: 'BAC',
    companyName: 'BAC Inc.',
    homeCountry: 'Common shareholders’ equity',
    sector: 'Financial Services',
    exposures: [
      { country: 'Common shareholders’ equity', percentage: 25.5, description: 'Revenue segment from 10-K' },
      { country: 'Long-term debt', percentage: 22.4, description: 'Revenue segment from 10-K' },
      { country: 'U.S. (3)', percentage: 12.5, description: 'Revenue segment from 10-K' },
      { country: 'Asia', percentage: 12.5, description: 'Revenue segment from 10-K' },
      { country: 'Latin America and the Caribbean', percentage: 12.5, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Average diluted common shares issued and outstanding', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Average common shares issued and outstanding', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Nonperforming loans, leases and foreclosed properties (5)', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Provision for credit losses', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Return on average assets (1)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Four-quarter trailing return on average assets (2)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Return on average common shareholders’ equity (1)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Return on average tangible common shareholders’ equity (3)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Return on average shareholders’ equity (1)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Return on average tangible shareholders’ equity (3)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Common equity ratio (1)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Dividend payout (1)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Diluted earnings', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Dividends paid', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Book value (1)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Tangible book value (3)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Annualized net charge-offs as a percentage of average loans and leases outstanding (5)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Common equity tier 1 capital', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Tier 1 capital', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Tier 1 leverage', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Supplementary leverage ratio', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Tangible equity (3)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Tangible common equity (3)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Eligible long-term debt to risk-weighted assets', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Eligible long-term debt to supplementary leverage exposure', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-25',
    lastUpdated: '2025-12-10'
  },
  'CRM': {
    ticker: 'CRM',
    companyName: 'CRM Inc.',
    homeCountry: '(in millions)',
    sector: 'Technology',
    exposures: [
      { country: '(in millions)', percentage: 13.7, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 8.6, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 8.6, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 8.6, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 8.6, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 8.6, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 8.6, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 8.6, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 3.3, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-03-05',
    lastUpdated: '2025-12-10'
  }
};