export const COMPANY_SPECIFIC_EXPOSURES: Record<string, CompanyExposure> = {
  'CVX': {
    ticker: 'CVX',
    companyName: 'CVX Inc.',
    homeCountry: 'Intersegment revenue elimination',
    sector: 'Unknown',
    exposures: [
      { country: 'Intersegment revenue elimination', percentage: 21, description: 'Revenue segment from 10-K' },
      { country: 'Transfers', percentage: 13.7, description: 'Revenue segment from 10-K' },
      { country: 'Supplemental Information on Oil and Gas Producing Activities', percentage: 9.1, description: 'Revenue segment from 10-K' },
      { country: 'Natural gas liquids, per barrel', percentage: 7.8, description: 'Revenue segment from 10-K' },
      { country: 'Reserves at January 1, 2022', percentage: 5.5, description: 'Revenue segment from 10-K' },
      { country: 'Depreciation, depletion and amortization', percentage: 5, description: 'Revenue segment from 10-K' },
      { country: 'Depreciation and depletion', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Reserves at December 31, 2023 4, 5', percentage: 4.2, description: 'Revenue segment from 10-K' },
      { country: 'Reserves at December 31, 2022 4, 5', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'Reserves at December 31, 2024 4, 5', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Reserves at December 31, 20233', percentage: 2.2, description: 'Revenue segment from 10-K' },
      { country: 'Reserves at December 31, 20243', percentage: 2.1, description: 'Revenue segment from 10-K' },
      { country: 'Reserves at December 31, 20223', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Purchases', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'All Other', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Natural gas, per thousand cubic feet', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Other costs and deductions3', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Extensions and discoveries', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Millions of dollars, except per-share amounts', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Millions of dollars', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Revisions', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Sales', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Unproved properties valuation', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Capital Employed', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Stockholders’ Equity', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Improved recovery', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-21',
    lastUpdated: '2025-12-10'
  },
  'TXN': {
    ticker: 'TXN',
    companyName: 'TXN Inc.',
    homeCountry: 'Europe, Middle East and Africa (a)',
    sector: 'Unknown',
    exposures: [
      { country: 'Europe, Middle East and Africa (a)', percentage: 36.3, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 31.1, description: 'Revenue segment from 10-K' },
      { country: 'Rest of Asia', percentage: 17.4, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 12.5, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 2.7, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-14',
    lastUpdated: '2025-12-10'
  },
  'MDT': {
    ticker: 'MDT',
    companyName: 'MDT Inc.',
    homeCountry: 'Reportable segment net sales',
    sector: 'Unknown',
    exposures: [
      { country: 'Reportable segment net sales', percentage: 46, description: 'Revenue segment from 10-K' },
      { country: 'Neuroscience', percentage: 16.3, description: 'Revenue segment from 10-K' },
      { country: 'Medical Surgical', percentage: 10.5, description: 'Revenue segment from 10-K' },
      { country: 'Cardiovascular', percentage: 6.7, description: 'Revenue segment from 10-K' },
      { country: '(in millions)', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Surgical & Endoscopy', percentage: 3.5, description: 'Revenue segment from 10-K' },
      { country: 'Diabetes', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Cranial & Spinal Technologies', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Structural Heart & Aortic', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Specialty Therapies', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Coronary & Peripheral Vascular', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'Neuromodulation', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Acute Care & Monitoring', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Other adjustments(2)', percentage: 0.1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-06-20',
    lastUpdated: '2025-12-10'
  },
  'HON': {
    ticker: 'HON',
    companyName: 'HON Inc.',
    homeCountry: 'Factors Contributing to Year-Over-Year Change',
    sector: 'Unknown',
    exposures: [
      { country: 'Factors Contributing to Year-Over-Year Change', percentage: 56.9, description: 'Revenue segment from 10-K' },
      { country: 'U.S. exports', percentage: 14.3, description: 'Revenue segment from 10-K' },
      { country: 'Other international', percentage: 6.8, description: 'Revenue segment from 10-K' },
      { country: '113', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: '110', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: '100', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: '95', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: '94', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: '92', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: '91', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: '88', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: '87', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: '85', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: '82', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: '80', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: '78', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: '77', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: '76', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: '72', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: '69', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: '66', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: '62', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Organic1', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Acquisitions, divestitures, and other, net', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Organic', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: '57', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Foreign currency translation', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-14',
    lastUpdated: '2025-12-10'
  },
  'UPS': {
    ticker: 'UPS',
    companyName: 'UPS Inc.',
    homeCountry: 'Compensation',
    sector: 'Unknown',
    exposures: [
      { country: 'Compensation', percentage: 21.8, description: 'Revenue segment from 10-K' },
      { country: 'Benefits', percentage: 17.9, description: 'Revenue segment from 10-K' },
      { country: 'Other segment items(1)', percentage: 17.3, description: 'Revenue segment from 10-K' },
      { country: 'Remeasurement of benefit obligation', percentage: 15.8, description: 'Revenue segment from 10-K' },
      { country: 'Foreign currency exchange contracts', percentage: 4.2, description: 'Revenue segment from 10-K' },
      { country: 'Purchased transportation', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Note 18—Transformation Strategy Costs', percentage: 1.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 17—Derivative Instruments and Risk Management', percentage: 1.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 16—Earnings Per Share', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 14—Segment and Geographic Information', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 13—Stock-Based Compensation', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 12—Shareowners’ Equity', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 11—Leases', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 10—Legal Proceedings and Contingencies', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 9—Debt and Financing Arrangements', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Note 8—Acquisitions and Dispositions', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Note 7—Goodwill and Intangible Assets', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Note 6—Multiemployer Employee Benefit Plans', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Note 5—Company-Sponsored Employee Benefit Plans', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 4—Property, Plant and Equipment', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 3—Marketable Securities and Non-Current Investments', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 2—Revenue Recognition', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 1—Summary of Accounting Policies', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Report of Independent Registered Public Accounting Firm  (PCAOB ID No. 34)', percentage: 0.7, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-18',
    lastUpdated: '2025-12-10'
  },
  'RTX': {
    ticker: 'RTX',
    companyName: 'RTX Inc.',
    homeCountry: 'Inter-segment sales',
    sector: 'Unknown',
    exposures: [
      { country: 'Inter-segment sales', percentage: 37.9, description: 'Revenue segment from 10-K' },
      { country: 'Commercial aerospace and other commercial sales', percentage: 16.2, description: 'Revenue segment from 10-K' },
      { country: 'Cost-type', percentage: 8.5, description: 'Revenue segment from 10-K' },
      { country: 'Commercial aerospace and other commercial sales (2)', percentage: 8.3, description: 'Revenue segment from 10-K' },
      { country: 'Other regions', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Foreign government direct commercial sales', percentage: 1.8, description: 'Revenue segment from 10-K' },
      { country: 'Middle East and North Africa', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: '(dollars in millions)', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Foreign military sales through the U.S. government', percentage: 0.6, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-03',
    lastUpdated: '2025-12-10'
  },
  'LOW': {
    ticker: 'LOW',
    companyName: 'LOW Inc.',
    homeCountry: 'Note 17: Segment Information',
    sector: 'Unknown',
    exposures: [
      { country: 'Note 17: Segment Information', percentage: 6.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 15: Related Parties', percentage: 6.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 16: Other Information', percentage: 6.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 13: Earnings Per Share', percentage: 6.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 14: Commitments and Contingencies', percentage: 6.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 11: Employee Retirement Plans', percentage: 6.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 10: Share-Based Payments', percentage: 5.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 9: Shareholders’ Deficit', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 8: Derivative Instruments', percentage: 5.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 7: Debt', percentage: 5.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 5: Leases', percentage: 5.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 6: Divestiture of the Canadian Retail Business', percentage: 5.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 4: Property and Accumulated Depreciation', percentage: 5.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 3: Fair Value Measurements', percentage: 5.1, description: 'Revenue segment from 10-K' },
      { country: 'Note 2: Revenue', percentage: 5, description: 'Revenue segment from 10-K' },
      { country: 'Note 1: Summary of Significant Accounting Policies', percentage: 4.3, description: 'Revenue segment from 10-K' },
      { country: 'Report of Independent Registered Public Accounting Firm (PCAOB ID No. 34)', percentage: 3.6, description: 'Revenue segment from 10-K' },
      { country: 'Management’s Report on Internal Control over Financial Reporting', percentage: 3.5, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-03-24',
    lastUpdated: '2025-12-10'
  },
  'SBUX': {
    ticker: 'SBUX',
    companyName: 'SBUX Inc.',
    homeCountry: 'Other countries',
    sector: 'Unknown',
    exposures: [
      { country: 'Other countries', percentage: 68.4, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 31.3, description: 'Revenue segment from 10-K' },
      { country: 'Fiscal Year Ended', percentage: 0.3, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-11-14',
    lastUpdated: '2025-12-10'
  },
  'AMGN': {
    ticker: 'AMGN',
    companyName: 'AMGN Inc.',
    homeCountry: 'ROW',
    sector: 'Unknown',
    exposures: [
      { country: 'ROW', percentage: 100, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-14',
    lastUpdated: '2025-12-10'
  },
  'GS': {
    ticker: 'GS',
    companyName: 'GS Inc.',
    homeCountry: 'Asia',
    sector: 'Unknown',
    exposures: [
      { country: 'Asia', percentage: 32.3, description: 'Revenue segment from 10-K' },
      { country: '$ in millions', percentage: 9.6, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 5.8, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-27',
    lastUpdated: '2025-12-10'
  },
  'BLK': {
    ticker: 'BLK',
    companyName: 'BLK Inc.',
    homeCountry: '(in millions)',
    sector: 'Unknown',
    exposures: [
      { country: '(in millions)', percentage: 100, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-25',
    lastUpdated: '2025-12-10'
  },
  'AXP': {
    ticker: 'AXP',
    companyName: 'AXP Inc.',
    homeCountry: 'Note 25 – Parent Company',
    sector: 'Unknown',
    exposures: [
      { country: 'Note 25 – Parent Company', percentage: 5.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 22 – Regulatory Matters and Capital Adequacy', percentage: 5.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 23 – Significant Credit Concentrations', percentage: 5.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 21 – Earnings Per Common Share (EPS)', percentage: 5.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 19 – Restructuring', percentage: 5.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 15 – Guarantees', percentage: 5.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 16 – Common and Preferred Shares', percentage: 5.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 14 – Fair Values', percentage: 5, description: 'Revenue segment from 10-K' },
      { country: 'Note 13 – Derivatives and Hedging Activities', percentage: 4.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 11 – Retirement Plans', percentage: 4.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 12 – Contingencies and Commitments', percentage: 4.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 9 – Other Liabilities', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 10 – Stock-Based Compensation', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 7 – Customer Deposits', percentage: 4.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 8 – Debt', percentage: 4.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 5 – Asset Securitizations', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 6 – Other Assets', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 4 – Investment Securities', percentage: 4.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 3 – Reserves for Credit Losses', percentage: 4.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 2 – Loans and Card Member Receivables', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 1 – Summary of Significant Accounting Policies', percentage: 3.6, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-07',
    lastUpdated: '2025-12-10'
  },
  'SPGI': {
    ticker: 'SPGI',
    companyName: 'SPGI Inc.',
    homeCountry: 'Recurring variable',
    sector: 'Unknown',
    exposures: [
      { country: 'Recurring variable', percentage: 24.7, description: 'Revenue segment from 10-K' },
      { country: 'Revenue', percentage: 19.3, description: 'Revenue segment from 10-K' },
      { country: 'Less: other segment items 3', percentage: 13.9, description: 'Revenue segment from 10-K' },
      { country: 'European region', percentage: 10.9, description: 'Revenue segment from 10-K' },
      { country: 'Non-subscription / Transaction', percentage: 9, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 6.8, description: 'Revenue segment from 10-K' },
      { country: 'Asia', percentage: 4.9, description: 'Revenue segment from 10-K' },
      { country: 'Subscription revenue', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'Rest of the world', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Non-subscription / transaction revenue', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Non-transaction revenue', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Asset-linked fees', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Sales usage-based royalties', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Intersegment revenue 1', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'U.S. revenue', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '(in millions)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'International revenue', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-11',
    lastUpdated: '2025-12-10'
  },
  'DE': {
    ticker: 'DE',
    companyName: 'DE Inc.',
    homeCountry: 'John C. May (55)',
    sector: 'Unknown',
    exposures: [
      { country: 'John C. May (55)', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Joshua A. Jepsen (47)', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Ryan D. Campbell (50)', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Jahmy J. Hindman (49)', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Rajesh Kalathur (56)', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Deanna M. Kovar (46)', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Felecia J. Pryor (50)', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Cory J. Reed (54)', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Justin R. Rose (45)', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Kellye L. Walker (58)', percentage: 10, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2024-12-12',
    lastUpdated: '2025-12-10'
  },
  'MMM': {
    ticker: 'MMM',
    companyName: 'MMM Inc.',
    homeCountry: 'NOTE 16. Supplier Finance Program Obligations',
    sector: 'Unknown',
    exposures: [
      { country: 'NOTE 16. Supplier Finance Program Obligations', percentage: 5.2, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 15. Pension and Postretirement Benefit Plans', percentage: 4.7, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 14. Long-Term Debt and Short-Term Borrowings', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 13. Marketable Securities', percentage: 4.5, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 12. Earnings (Loss) Per Share', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 10. Supplemental Cash Flow Information', percentage: 4.2, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 8. Supplemental Balance Sheet Information', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 6. Restructuring Actions', percentage: 4, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 3. Revenue', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 4. Divestitures', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 5. Goodwill and Intangible Assets', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 2. Discontinued Operations', percentage: 3.6, description: 'Revenue segment from 10-K' },
      { country: 'NOTE 1. Significant Accounting Policies', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Report of Independent Registered Public Accounting Firm', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Financial Instruments', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Item 7A. Quantitative and Qualitative Disclosures About Market Risk', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Item 8. Financial Statements and Supplementary Data', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Index to Financial Statements', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Management’s Responsibility for Financial Reporting', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Management’s Report on Internal Control Over Financial Reporting', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'New Accounting Pronouncements', percentage: 2.5, description: 'Revenue segment from 10-K' },
      { country: 'Financial Condition and Liquidity', percentage: 2.5, description: 'Revenue segment from 10-K' },
      { country: 'Performance by Geographic Area', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Critical Accounting Estimates', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Performance by Business Segment', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Results of Operations', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Item 6. [Reserved]', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Item 7. Management’s Discussion and Analysis of Financial Condition and Results of Operations', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Overview', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Item 2. Properties', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Item 3. Legal Proceedings', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Item 4. Mine Safety Disclosures', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'PART II', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Item 5. Market for Registrant’s Common Equity, Related Stockholder Matters and Issuer Purchases of Equity Securities', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Item 1B. Unresolved Staff Comments', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Item 1C. Cybersecurity', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Item 1A. Risk Factors', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'PART I', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Item 1. Business', percentage: 0.3, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-05',
    lastUpdated: '2025-12-10'
  }
};