export const COMPANY_SPECIFIC_EXPOSURES: Record<string, CompanyExposure> = {
  'CL': {
    ticker: 'CL',
    companyName: 'CL Inc.',
    homeCountry: 'Europe(1)',
    sector: 'Unknown',
    exposures: [
      { country: 'Europe(1)', percentage: 29.4, description: 'Revenue segment from 10-K' },
      { country: 'Pet Nutrition', percentage: 28.6, description: 'Revenue segment from 10-K' },
      { country: 'Brazil', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Argentina', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Chile', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Colombia', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Peru', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'North America(1)', percentage: 3.7, description: 'Revenue segment from 10-K' },
      { country: 'Africa/Eurasia', percentage: 3.1, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 1.1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-13',
    lastUpdated: '2025-12-10'
  },
  'MDLZ': {
    ticker: 'MDLZ',
    companyName: 'MDLZ Inc.',
    homeCountry: 'Gum & Candy',
    sector: 'Unknown',
    exposures: [
      { country: 'Gum & Candy', percentage: 22.5, description: 'Revenue segment from 10-K' },
      { country: 'Chocolate', percentage: 21.6, description: 'Revenue segment from 10-K' },
      { country: 'Effective tax rate', percentage: 9.1, description: 'Revenue segment from 10-K' },
      { country: 'U.S. federal statutory rate', percentage: 8.1, description: 'Revenue segment from 10-K' },
      { country: 'Beverages', percentage: 8, description: 'Revenue segment from 10-K' },
      { country: 'Cheese & Grocery', percentage: 8, description: 'Revenue segment from 10-K' },
      { country: 'AMEA', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Canada', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Foreign rate differences', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Tax benefit from legal entity reorganization', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Net change in tax accruals', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Foreign tax provisions under TCJA (GILTI, FDII and BEAT) (1)', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Excess tax benefits from equity compensation', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Changes in judgment on realizability of deferred tax assets', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Tax legislation', percentage: 0.1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-05',
    lastUpdated: '2025-12-10'
  },
  'EQIX': {
    ticker: 'EQIX',
    companyName: 'EQIX Inc.',
    homeCountry: 'Recurring revenues',
    sector: 'Unknown',
    exposures: [
      { country: 'Recurring revenues', percentage: 84.6, description: 'Revenue segment from 10-K' },
      { country: 'Interconnection', percentage: 9.2, description: 'Revenue segment from 10-K' },
      { country: 'Non-recurring revenues', percentage: 3.2, description: 'Revenue segment from 10-K' },
      { country: 'Managed infrastructure', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Other (1)', percentage: 0.3, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-12',
    lastUpdated: '2025-12-10'
  },
  'BDX': {
    ticker: 'BDX',
    companyName: 'BDX Inc.',
    homeCountry: 'Greater Asia',
    sector: 'Unknown',
    exposures: [
      { country: 'Greater Asia', percentage: 20.8, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 16.4, description: 'Revenue segment from 10-K' },
      { country: '(Millions of dollars)', percentage: 13.6, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Corporate', percentage: 3.4, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-11-25',
    lastUpdated: '2025-12-10'
  },
  'VRTX': {
    ticker: 'VRTX',
    companyName: 'VRTX Inc.',
    homeCountry: 'United States',
    sector: 'Unknown',
    exposures: [
      { country: 'United States', percentage: 20.3, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 11.4, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 11.4, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 11.4, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 11.4, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 11.4, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 11.4, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 11.4, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-13',
    lastUpdated: '2025-12-10'
  },
  'ADI': {
    ticker: 'ADI',
    companyName: 'ADI Inc.',
    homeCountry: 'China',
    sector: 'Unknown',
    exposures: [
      { country: 'China', percentage: 33.8, description: 'Revenue segment from 10-K' },
      { country: 'Rest of Asia', percentage: 17.6, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 11.7, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Ireland', percentage: 3.5, description: 'Revenue segment from 10-K' },
      { country: 'Philippines', percentage: 2.4, description: 'Revenue segment from 10-K' },
      { country: 'Rest of North and South America', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Thailand', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'All other regions', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Malaysia', percentage: 0.2, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-11-25',
    lastUpdated: '2025-12-10'
  },
  'APD': {
    ticker: 'APD',
    companyName: 'APD Inc.',
    homeCountry: 'Energy cost pass-through to customers',
    sector: 'Unknown',
    exposures: [
      { country: 'Energy cost pass-through to customers', percentage: 28.4, description: 'Revenue segment from 10-K' },
      { country: 'Price', percentage: 26.7, description: 'Revenue segment from 10-K' },
      { country: 'Volume', percentage: 23.4, description: 'Revenue segment from 10-K' },
      { country: 'Currency', percentage: 21.7, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-11-20',
    lastUpdated: '2025-12-10'
  },
  'SHW': {
    ticker: 'SHW',
    companyName: 'SHW Inc.',
    homeCountry: 'as a percent of Net sales',
    sector: 'Unknown',
    exposures: [
      { country: 'as a percent of Net sales', percentage: 100, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-20',
    lastUpdated: '2025-12-10'
  },
  'KLAC': {
    ticker: 'KLAC',
    companyName: 'KLAC Inc.',
    homeCountry: '(In thousands)',
    sector: 'Unknown',
    exposures: [
      { country: '(In thousands)', percentage: 32.9, description: 'Revenue segment from 10-K' },
      { country: 'PCB and Component Inspection', percentage: 17.1, description: 'Revenue segment from 10-K' },
      { country: 'Specialty Semiconductor Process', percentage: 16.2, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 13.2, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 6, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 4.7, description: 'Revenue segment from 10-K' },
      { country: 'Europe and Israel', percentage: 2.4, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Canada', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Rest of Asia', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Corporate allocations and effects of changes in foreign currency exchange rates', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: '(Dollar amounts in thousands)', percentage: 0.1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-08-08',
    lastUpdated: '2025-12-10'
  },
  'MCO': {
    ticker: 'MCO',
    companyName: 'MCO Inc.',
    homeCountry: '2022 - 2023 Geolocation Restructuring Program',
    sector: 'Unknown',
    exposures: [
      { country: '2022 - 2023 Geolocation Restructuring Program', percentage: 15.3, description: 'Revenue segment from 10-K' },
      { country: 'Non-U.S.', percentage: 14.3, description: 'Revenue segment from 10-K' },
      { country: 'Strategic and Operational Efficiency Restructuring Program', percentage: 9.7, description: 'Revenue segment from 10-K' },
      { country: 'EU AI Act', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'GCR (Global Credit Rating Company Limited and subsidiaries)', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'GDPR', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'GLoBE', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'KMV', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'Exchange Act', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Data and Information (D&I)', percentage: 3.7, description: 'Revenue segment from 10-K' },
      { country: 'Other accounts (1)', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Insurance', percentage: 2.6, description: 'Revenue segment from 10-K' },
      { country: 'Bank loans', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Investment-grade', percentage: 2.1, description: 'Revenue segment from 10-K' },
      { country: 'Banking', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'KYC', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Project and infrastructure', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'High-yield', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Public finance / sovereign', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Eliminations', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Structured credit', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Intersegment royalty', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'kompany', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Asset-backed securities', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'RMBS', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'CMBS', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Canada', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Brazil', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Argentina', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Chile', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Managed investments', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'MIS Other', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Intersegment revenue', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Other accounts (FIG)', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Other accounts (SFG)', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-14',
    lastUpdated: '2025-12-10'
  },
  'ITW': {
    ticker: 'ITW',
    companyName: 'ITW Inc.',
    homeCountry: 'In millions',
    sector: 'Unknown',
    exposures: [
      { country: 'In millions', percentage: 18.5, description: 'Revenue segment from 10-K' },
      { country: 'Test & Measurement and Electronics', percentage: 16.9, description: 'Revenue segment from 10-K' },
      { country: 'Food Equipment', percentage: 15.9, description: 'Revenue segment from 10-K' },
      { country: 'Welding', percentage: 11.1, description: 'Revenue segment from 10-K' },
      { country: 'Polymers & Fluids', percentage: 10.6, description: 'Revenue segment from 10-K' },
      { country: 'Canada/Mexico', percentage: 3.7, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Brazil', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Argentina', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Chile', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Colombia', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Peru', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Intersegment revenue', percentage: 0.1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-14',
    lastUpdated: '2025-12-10'
  },
  'FCX': {
    ticker: 'FCX',
    companyName: 'FCX Inc.',
    homeCountry: 'Japan',
    sector: 'Unknown',
    exposures: [
      { country: 'Japan', percentage: 33.6, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 24.1, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 6.3, description: 'Revenue segment from 10-K' },
      { country: 'Indonesia', percentage: 6.3, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 6.1, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 6, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 4.2, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Chile', percentage: 2.6, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Philippines', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 1.5, description: 'Revenue segment from 10-K' },
      { country: 'Egypt', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 0.7, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-14',
    lastUpdated: '2025-12-10'
  },
  'EMR': {
    ticker: 'EMR',
    companyName: 'EMR Inc.',
    homeCountry: 'Eliminations/Interest',
    sector: 'Unknown',
    exposures: [
      { country: 'Eliminations/Interest', percentage: 100, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-11-10',
    lastUpdated: '2025-12-10'
  }
};