export const COMPANY_SPECIFIC_EXPOSURES: Record<string, CompanyExposure> = {
  'ISRG': {
    ticker: 'ISRG',
    companyName: 'ISRG Inc.',
    homeCountry: 'OUS',
    sector: 'Unknown',
    exposures: [
      { country: 'OUS', percentage: 33.9, description: 'Revenue segment from 10-K' },
      { country: 'Systems', percentage: 24.1, description: 'Revenue segment from 10-K' },
      { country: 'Unit placements not involving trade-ins', percentage: 16.9, description: 'Revenue segment from 10-K' },
      { country: 'U.S. unit placements', percentage: 9.8, description: 'Revenue segment from 10-K' },
      { country: 'OUS unit placements', percentage: 8.9, description: 'Revenue segment from 10-K' },
      { country: 'Ion System Placements**', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'Unit placements involving trade-ins', percentage: 1.8, description: 'Revenue segment from 10-K' },
      { country: '% of Revenue — U.S.', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: '% of Revenue — OUS', percentage: 0.4, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-01-31',
    lastUpdated: '2025-12-10'
  },
  'TJX': {
    ticker: 'TJX',
    companyName: 'TJX Inc.',
    homeCountry: 'U.S. dollars in millions',
    sector: 'Unknown',
    exposures: [
      { country: 'U.S. dollars in millions', percentage: 37.8, description: 'Revenue segment from 10-K' },
      { country: 'U.S. dollars in millions', percentage: 34.8, description: 'Revenue segment from 10-K' },
      { country: 'In millions', percentage: 20, description: 'Revenue segment from 10-K' },
      { country: 'Marshalls', percentage: 1.8, description: 'Revenue segment from 10-K' },
      { country: 'TJ Maxx', percentage: 1.8, description: 'Revenue segment from 10-K' },
      { country: 'HomeGoods', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'TK Maxx', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Winners', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'HomeSense', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Homesense', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Sierra', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'TK Maxx Australia', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Segment profit margin', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Comp store sales', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-04-02',
    lastUpdated: '2025-12-10'
  },
  'ZTS': {
    ticker: 'ZTS',
    companyName: 'ZTS Inc.',
    homeCountry: 'United States',
    sector: 'Unknown',
    exposures: [
      { country: 'United States', percentage: 55.4, description: 'Revenue segment from 10-K' },
      { country: 'Other Emerging', percentage: 9.4, description: 'Revenue segment from 10-K' },
      { country: 'Other Developed', percentage: 6.1, description: 'Revenue segment from 10-K' },
      { country: 'Brazil', percentage: 4.5, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 3.5, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Canada', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 2.9, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 2.5, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 1.8, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'Chile', percentage: 1.3, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-13',
    lastUpdated: '2025-12-10'
  },
  'CB': {
    ticker: 'CB',
    companyName: 'CB Inc.',
    homeCountry: 'Net premiums earned',
    sector: 'Unknown',
    exposures: [
      { country: 'Net premiums earned', percentage: 71.1, description: 'Revenue segment from 10-K' },
      { country: 'Policy acquisition costs', percentage: 13, description: 'Revenue segment from 10-K' },
      { country: 'Policy benefits (includes remeasurement gains (losses) of $(2), $19, and $3)', percentage: 6.7, description: 'Revenue segment from 10-K' },
      { country: '(in millions of U.S. dollars, except per share data)', percentage: 2.9, description: 'Revenue segment from 10-K' },
      { country: 'Increase in unearned premiums', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Cumulative foreign currency translation adjustment', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Current discount rate on future policy benefits', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Amortization of purchased intangibles', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Other, including postretirement benefit liability adjustment', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Net realized gains (losses)', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Market risk benefits gains (losses)', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Instrument-specific credit risk on market risk benefits', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-27',
    lastUpdated: '2025-12-10'
  },
  'SYK': {
    ticker: 'SYK',
    companyName: 'SYK Inc.',
    homeCountry: 'Orthopaedics',
    sector: 'Unknown',
    exposures: [
      { country: 'Orthopaedics', percentage: 40.4, description: 'Revenue segment from 10-K' },
      { country: 'Europe, Middle East, Africa', percentage: 12.8, description: 'Revenue segment from 10-K' },
      { country: 'Medical', percentage: 5, description: 'Revenue segment from 10-K' },
      { country: 'Trauma and Extremities', percentage: 4.5, description: 'Revenue segment from 10-K' },
      { country: 'Endoscopy', percentage: 4.4, description: 'Revenue segment from 10-K' },
      { country: 'Other countries', percentage: 3.2, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Neuro Cranial', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'MedSurg and Neurotechnology:', percentage: 2.6, description: 'Revenue segment from 10-K' },
      { country: 'Hips', percentage: 2.2, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Neurovascular', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Spinal Implants', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 0.9, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-12',
    lastUpdated: '2025-12-10'
  },
  'DUK': {
    ticker: 'DUK',
    companyName: 'DUK Inc.',
    homeCountry: 'Segment assets',
    sector: 'Unknown',
    exposures: [
      { country: 'Segment assets', percentage: 45.2, description: 'Revenue segment from 10-K' },
      { country: 'Segment assets(f)', percentage: 23.2, description: 'Revenue segment from 10-K' },
      { country: '10.15', percentage: 7.2, description: 'Revenue segment from 10-K' },
      { country: 'Operation, maintenance and other', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Depreciation and amortization', percentage: 2.1, description: 'Revenue segment from 10-K' },
      { country: '10.61', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Property and other taxes', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: '10.55', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: '10.56', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: '10.56.1', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 23 – Employee Benefit Plans', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 20 – Stockholders' Equity', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 21 – Severance', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 22 – Stock-Based Compensation', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 19 – Revenue', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 18 – Variable Interest Entities', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 17 – Fair Value Measurements', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 16 – Investments in Debt and Equity Securities', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 14 – Related Party Transactions', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 15 – Derivatives and Hedging', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 11 – Property, Plant and Equipment', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 12 – Goodwill and Intangible Assets', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 8 – Guarantees and Indemnifications', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 9 – Joint Ownership of Generating and Transmission Facilities', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 10 – Asset Retirement Obligations', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 7 – Debt and Credit Facilities', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 6 – Leases', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 5 – Commitments and Contingencies', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 4 – Regulatory Matters', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 2 – Dispositions', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 3 – Business Segments', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 1 – Summary of Significant Accounting Policies', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Add: Other(b)', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Add: Other segment items(a)', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Impairment of assets and other charges', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Intersegment revenues', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Noncontrolling interests(a)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.3.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.4.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.5.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.5.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.5.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.5.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.8.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.11', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.11.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.11.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.13', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.14', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.15', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.16', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.17', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.18', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.19', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.20', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '3.21', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.9', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.10', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.11', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.12', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.13', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.14', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.15', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.16', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.17', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.18', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.19', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.20', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.21', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.22', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.23', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.24', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.25', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.26', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.27', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.28', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.29', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.30', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.31', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.32', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.1.33', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.3.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.3.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.9', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.10', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.11', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.12', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.13', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.14', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.15', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.16', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.17', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.18', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.19', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.20', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.21', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.22', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.23', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.24', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.25', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.26', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.27', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.28', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.29', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.4.30', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.9', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.10', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.11', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.12', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.13', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.14', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.15', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.16', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.17', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.18', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.19', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.20', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.21', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.22', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.23', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.24', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.25', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.26', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.27', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.28', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.29', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.30', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.31', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.32', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.33', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.34', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.35', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.36', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.37', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.38', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.39', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.40', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.41', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.42', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.43', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.44', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.45', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.46', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.47', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.48', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.49', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.50', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.51', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.52', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.53', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.54', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.55', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.56', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.57', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.58', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.59', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.60', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.61', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.62', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.63', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.64', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.65', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.66', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.67', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.68', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.69', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.70', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.71', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.72', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.73', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.74', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.75', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.76', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.77', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.78', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.79', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.80', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.81', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.82', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.83', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.84', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.85', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.86', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.87', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.5.88', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.9', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.10', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.11', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.12', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.13', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.14', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.15', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.16', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.17', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.18', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.19', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.20', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.21', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.22', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.23', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.8.24', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.9.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.9.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.10', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.11.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.11.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.12.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.12.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.12.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.12.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.12.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.12.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.12.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.12.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.13.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.13.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.133', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.13.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.9', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.10', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.11', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.12', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.13', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.14', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.15', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.16', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.17', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.18', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.19', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.20', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.21', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.22', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.23', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.24', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.25', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.14.26', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.17', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.18', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.19', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.20', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.21', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.22', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.23', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.9', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.10', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.24.11', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.25', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.26', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.27', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.28', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.29', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '4.30', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.10', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.11**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.12**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.14**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.14.1**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.15.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.16**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.16.1**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.17**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.18**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.19**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.20**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.21**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.22**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.23**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.24**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.25**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.26', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.27', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.28', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.29', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.30', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.32', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.33**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.33.1**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.34**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.34.1**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.35', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.36', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.37', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.38', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.42**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.43**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.44**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.45**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.46**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.46.1**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.46.2**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.47**', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.51', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.52', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.57', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.58', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.59', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.60', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.61.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.62', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.63', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.63.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.63.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.64', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.65', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.66', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.68', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.69', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.70', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.71', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '10.72', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*19', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.1.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.1.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.1.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.1.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.1.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.1.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.1.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.1.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.2.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.2.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.2.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.2.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.2.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.2.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.2.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*31.2.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.1.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.1.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.1.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.1.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.1.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.1.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.1.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.1.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.2.1', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.2.2', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.2.3', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.2.4', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.2.5', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.2.6', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.2.7', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*32.2.8', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: '*104', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-27',
    lastUpdated: '2025-12-10'
  },
  'SO': {
    ticker: 'SO',
    companyName: 'SO Inc.',
    homeCountry: 'PPA energy revenues',
    sector: 'Unknown',
    exposures: [
      { country: 'PPA energy revenues', percentage: 14.9, description: 'Revenue segment from 10-K' },
      { country: 'Commercial', percentage: 14, description: 'Revenue segment from 10-K' },
      { country: 'Industrial', percentage: 8.8, description: 'Revenue segment from 10-K' },
      { country: 'Other segment items(a)(b)', percentage: 7, description: 'Revenue segment from 10-K' },
      { country: 'Other segment items(a)(c)', percentage: 5.6, description: 'Revenue segment from 10-K' },
      { country: 'Other segment items(a)(c)(d)', percentage: 5.2, description: 'Revenue segment from 10-K' },
      { country: 'Residential', percentage: 5.1, description: 'Revenue segment from 10-K' },
      { country: 'Other segment items(a)(c)(i)(j)', percentage: 4.6, description: 'Revenue segment from 10-K' },
      { country: 'Depreciation and amortization', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Other segment items(a)(b)(c)(d)', percentage: 3.6, description: 'Revenue segment from 10-K' },
      { country: 'Other revenues', percentage: 3.6, description: 'Revenue segment from 10-K' },
      { country: 'Other segment items(a)(c)(g)(h)', percentage: 3.5, description: 'Revenue segment from 10-K' },
      { country: 'Utility operations and maintenance', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'Other segment items(a)', percentage: 3.2, description: 'Revenue segment from 10-K' },
      { country: 'Non-PPA revenues', percentage: 2.9, description: 'Revenue segment from 10-K' },
      { country: 'Transportation', percentage: 2.9, description: 'Revenue segment from 10-K' },
      { country: 'Other revenue sources(*)', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'PPA capacity revenues', percentage: 1.5, description: 'Revenue segment from 10-K' },
      { country: 'Depreciation and amortization(e)', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Depreciation and amortization', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Depreciation and amortization', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Earnings from equity method investments', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-20',
    lastUpdated: '2025-12-10'
  },
  'BSX': {
    ticker: 'BSX',
    companyName: 'BSX Inc.',
    homeCountry: 'Geographic Regions',
    sector: 'Unknown',
    exposures: [
      { country: 'Geographic Regions', percentage: 23.6, description: 'Revenue segment from 10-K' },
      { country: 'Latin America and Canada', percentage: 7.3, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 3.8, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-18',
    lastUpdated: '2025-12-10'
  },
  'C': {
    ticker: 'C',
    companyName: 'C Inc.',
    homeCountry: 'Japan, Asia North and Australia (JANA)',
    sector: 'Unknown',
    exposures: [
      { country: 'Japan, Asia North and Australia (JANA)', percentage: 16.4, description: 'Revenue segment from 10-K' },
      { country: 'Asia South', percentage: 14.6, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 9.5, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 9.5, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 9.5, description: 'Revenue segment from 10-K' },
      { country: 'LATAM', percentage: 8.7, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 8.4, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 8.4, description: 'Revenue segment from 10-K' },
      { country: 'Middle East and Africa (MEA)', percentage: 6.8, description: 'Revenue segment from 10-K' },
      { country: 'Deposits', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Loans', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Average trading account assets', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'U.S. dollar clearing volume (in millions)(4)', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Average deposits', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'ACLL as a percentage of EOP loans(3)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'NCLs as a percentage of average loans', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'ACLL as a percentage of EOP loans(5)', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'ACLL as a percentage of EOP loans', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-21',
    lastUpdated: '2025-12-10'
  },
  'LRCX': {
    ticker: 'LRCX',
    companyName: 'LRCX Inc.',
    homeCountry: 'South Korea',
    sector: 'Unknown',
    exposures: [
      { country: 'South Korea', percentage: 27.8, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 23.6, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 17, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 12.7, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 9.1, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Thailand', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Malaysia', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Indonesia', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Philippines', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Vietnam', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 0.5, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-08-11',
    lastUpdated: '2025-12-10'
  },
  'SCHW': {
    ticker: 'SCHW',
    companyName: 'SCHW Inc.',
    homeCountry: 'Management’s Report on Internal Control Over Financial Reporting',
    sector: 'Unknown',
    exposures: [
      { country: 'Management’s Report on Internal Control Over Financial Reporting', percentage: 50.4, description: 'Revenue segment from 10-K' },
      { country: 'Report of Independent Registered Public Accounting Firm (PCAOB ID No. 34)', percentage: 49.6, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-26',
    lastUpdated: '2025-12-10'
  },
  'PNC': {
    ticker: 'PNC',
    companyName: 'PNC Inc.',
    homeCountry: 'Interest-bearing',
    sector: 'Unknown',
    exposures: [
      { country: 'Interest-bearing', percentage: 53.2, description: 'Revenue segment from 10-K' },
      { country: 'SIGNATURES', percentage: 23.8, description: 'Revenue segment from 10-K' },
      { country: 'Commercial real estate', percentage: 5.5, description: 'Revenue segment from 10-K' },
      { country: 'Other consumer', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Home equity', percentage: 2.2, description: 'Revenue segment from 10-K' },
      { country: 'Pretax earnings', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Commercial', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Dollars in millions, except as noted', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Automobile', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'Item 16', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Equipment lease financing', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Segment allocations (a)', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Personnel', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Credit card', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Dollars in millions', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Other (b)', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Education', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Nondiscretionary client assets under administration', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Provision for credit losses', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Depreciation and amortization', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Efficiency', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Institutional Asset Management', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Noncontrolling interests', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Return on average assets', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Consumer', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Provision for (recapture of) credit losses', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Brokerage fees', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-21',
    lastUpdated: '2025-12-10'
  }
};