export const COMPANY_SPECIFIC_EXPOSURES: Record<string, CompanyExposure> = {
  'CMCSA': {
    ticker: 'CMCSA',
    companyName: 'CMCSA Inc.',
    homeCountry: 'Other(d)',
    sector: 'Communication Services',
    exposures: [
      { country: 'Other(d)', percentage: 59.6, description: 'Revenue segment from 10-K' },
      { country: 'Video', percentage: 5.7, description: 'Revenue segment from 10-K' },
      { country: 'Domestic distribution', percentage: 2.5, description: 'Revenue segment from 10-K' },
      { country: 'Domestic advertising', percentage: 2.1, description: 'Revenue segment from 10-K' },
      { country: 'Eliminations(a)', percentage: 1.8, description: 'Revenue segment from 10-K' },
      { country: 'Content licensing', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 13: Supplemental Financial Information', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 14: Commitments and Contingencies', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 12: Share-Based Compensation', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 11: Equity', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 10: Employee Benefit Plans', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 9: Goodwill and Intangible Assets', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 8: Property and Equipment', percentage: 1.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 7: Investments and Variable Interest Entities', percentage: 1.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 6: Debt', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 3: Revenue', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 1: Summary of Significant Accounting Policies', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 2: Segment Information', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Report of Independent Registered Public Accounting Firm', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Report of Management', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'International connectivity', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Domestic wireless', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'International networks', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Advertising', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Other revenue(a)', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Intersegment revenue(a)', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Year ended December 31 (in millions)', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Theatrical', percentage: 0.4, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-01-31',
    lastUpdated: '2025-12-10'
  },
  'XOM': {
    ticker: 'XOM',
    companyName: 'XOM Inc.',
    homeCountry: 'Future cash inflows from sales of oil and gas',
    sector: 'Energy',
    exposures: [
      { country: 'Future cash inflows from sales of oil and gas', percentage: 11.5, description: 'Revenue segment from 10-K' },
      { country: 'December 31, 2024', percentage: 10.1, description: 'Revenue segment from 10-K' },
      { country: 'Revenue', percentage: 9.3, description: 'Revenue segment from 10-K' },
      { country: 'January 1, 2024', percentage: 6.9, description: 'Revenue segment from 10-K' },
      { country: 'Transfers', percentage: 5.5, description: 'Revenue segment from 10-K' },
      { country: 'Future net cash flows', percentage: 5.3, description: 'Revenue segment from 10-K' },
      { country: 'Non-U.S.', percentage: 5.3, description: 'Revenue segment from 10-K' },
      { country: 'January 1, 2022', percentage: 5.2, description: 'Revenue segment from 10-K' },
      { country: 'December 31, 2022', percentage: 4.8, description: 'Revenue segment from 10-K' },
      { country: 'January 1, 2023', percentage: 4.8, description: 'Revenue segment from 10-K' },
      { country: 'December 31, 2023', percentage: 4.5, description: 'Revenue segment from 10-K' },
      { country: 'Sales to third parties', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 3.7, description: 'Revenue segment from 10-K' },
      { country: 'Depreciation and depletion', percentage: 3.5, description: 'Revenue segment from 10-K' },
      { country: 'Extensions/discoveries', percentage: 2.9, description: 'Revenue segment from 10-K' },
      { country: 'Purchases', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Effect of discounting net cash flows at 10%', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Discounted future net cash flows', percentage: 2.6, description: 'Revenue segment from 10-K' },
      { country: 'Revisions', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Canada', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Sales', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Revisions (1)', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Revisions (2)', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Results of producing activities for equity companies', percentage: 0.1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-19',
    lastUpdated: '2025-12-10'
  },
  'PFE': {
    ticker: 'PFE',
    companyName: 'PFE Inc.',
    homeCountry: 'Int’l.',
    sector: 'Healthcare',
    exposures: [
      { country: 'Int’l.', percentage: 100, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-27',
    lastUpdated: '2025-12-10'
  },
  'CSCO': {
    ticker: 'CSCO',
    companyName: 'CSCO Inc.',
    homeCountry: 'APJC',
    sector: 'Technology',
    exposures: [
      { country: 'APJC', percentage: 19.1, description: 'Revenue segment from 10-K' },
      { country: 'Note 21: Subsequent Event', percentage: 3.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 19: Segment Information and Major Customers', percentage: 3.2, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Note 16: Employee Benefit Plans', percentage: 3, description: 'Revenue segment from 10-K' },
      { country: 'Note 15: Stockholders’ Equity', percentage: 2.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 14: Commitments and Contingencies', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 13: Derivative Instruments', percentage: 2.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 11: Fair Value', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 12: Borrowings', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 10: Investments', percentage: 2.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 9: Financing Receivables', percentage: 2.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 8: Leases', percentage: 2.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 6: Restructuring and Other Charges', percentage: 2.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 7: Balance Sheet and Other Details', percentage: 2.4, description: 'Revenue segment from 10-K' },
      { country: 'Note 5: Goodwill and Purchased Intangible Assets', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 4: Acquisitions', percentage: 2.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 3: Revenue', percentage: 2.1, description: 'Revenue segment from 10-K' },
      { country: 'Note 1: Basis of Presentation', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 2: Summary of Significant Accounting Policies', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Reports of Management', percentage: 1.8, description: 'Revenue segment from 10-K' },
      { country: 'Report of Independent Registered Public Accounting Firm (PCAOB ID 238)', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Percentage of service revenue', percentage: 0.5, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-09-03',
    lastUpdated: '2025-12-10'
  },
  'VZ': {
    ticker: 'VZ',
    companyName: 'VZ Inc.',
    homeCountry: 'Corporate and other',
    sector: 'Communication Services',
    exposures: [
      { country: 'Corporate and other', percentage: 53.4, description: 'Revenue segment from 10-K' },
      { country: 'Years Ended December 31,', percentage: 41.4, description: 'Revenue segment from 10-K' },
      { country: 'Eliminations', percentage: 5.2, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-12',
    lastUpdated: '2025-12-10'
  },
  'KO': {
    ticker: 'KO',
    companyName: 'KO Inc.',
    homeCountry: 'Bottling Investments',
    sector: 'Consumer Defensive',
    exposures: [
      { country: 'Bottling Investments', percentage: 38.3, description: 'Revenue segment from 10-K' },
      { country: 'Report of Independent Registered Public Accounting Firm on Internal Control Over Financial Reporting', percentage: 16.9, description: 'Revenue segment from 10-K' },
      { country: 'Report of Independent Registered Public Accounting Firm (PCAOB ID: 42)', percentage: 16.6, description: 'Revenue segment from 10-K' },
      { country: 'Report of Management', percentage: 16.4, description: 'Revenue segment from 10-K' },
      { country: 'Global Ventures', percentage: 3.3, description: 'Revenue segment from 10-K' },
      { country: 'Worldwide', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Brazil', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Argentina', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Chile', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Colombia', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Peru', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 0.2, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-20',
    lastUpdated: '2025-12-10'
  },
  'PEP': {
    ticker: 'PEP',
    companyName: 'PEP Inc.',
    homeCountry: 'All other countries',
    sector: 'Consumer Defensive',
    exposures: [
      { country: 'All other countries', percentage: 21.2, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 8.8, description: 'Revenue segment from 10-K' },
      { country: 'Russia', percentage: 4.8, description: 'Revenue segment from 10-K' },
      { country: 'Canada', percentage: 4.7, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 3.5, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 2.7, description: 'Revenue segment from 10-K' },
      { country: 'GLOSSARY', percentage: 2.4, description: 'Revenue segment from 10-K' },
      { country: 'REPORT OF INDEPENDENT REGISTERED PUBLIC ACCOUNTING FIRM', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 14 – Supply Chain Financing Arrangements', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 15 – Supplemental Financial Information', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 16 – Legal Contingencies', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 2.3, description: 'Revenue segment from 10-K' },
      { country: 'Note 13 – Acquisitions and Divestitures', percentage: 2.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 11 – Accumulated Other Comprehensive Loss Attributable to PepsiCo', percentage: 2.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 12 – Leases', percentage: 2.2, description: 'Revenue segment from 10-K' },
      { country: 'Brazil', percentage: 2.2, description: 'Revenue segment from 10-K' },
      { country: 'Note 9 – Financial Instruments', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Note 8 – Debt Obligations', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Note 7 – Pension, Retiree Medical and Savings Plans', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 6 – Share-Based Compensation', percentage: 1.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 4 – Intangible Assets', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 3 – Restructuring and Impairment Charges', percentage: 1.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 2 – Our Significant Accounting Policies', percentage: 1.5, description: 'Revenue segment from 10-K' },
      { country: 'Note 1 – Basis of Presentation and Our Divisions', percentage: 1.3, description: 'Revenue segment from 10-K' },
      { country: 'Pension and Retiree Medical Plans', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Revenue Recognition', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Goodwill and Other Intangible Assets', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Return on Invested Capital', percentage: 1.1, description: 'Revenue segment from 10-K' },
      { country: 'Our Liquidity and Capital Resources', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Items Affecting Comparability', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'LatAm', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'AMESA', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Non-GAAP Measures', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Results of Operations – Division Review', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'FLNA', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'QFNA', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'PBNA', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Other Relationships', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Our Business Risks', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Executive Overview', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Our Operations', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'South Korea', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Australia', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'India', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 0.1, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-04',
    lastUpdated: '2025-12-10'
  },
  'T': {
    ticker: 'T',
    companyName: 'T Inc.',
    homeCountry: 'Wireless service',
    sector: 'Communication Services',
    exposures: [
      { country: 'Wireless service', percentage: 31.3, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 28.9, description: 'Revenue segment from 10-K' },
      { country: 'At or for the years ended December 31,', percentage: 13.6, description: 'Revenue segment from 10-K' },
      { country: 'Equipment', percentage: 10, description: 'Revenue segment from 10-K' },
      { country: 'Business service', percentage: 8.8, description: 'Revenue segment from 10-K' },
      { country: 'Asia/Pacific Rim', percentage: 3.1, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Brazil', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Argentina', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Chile', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Colombia', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Peru', percentage: 0.2, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-12',
    lastUpdated: '2025-12-10'
  },
  'ABT': {
    ticker: 'ABT',
    companyName: 'ABT Inc.',
    homeCountry: '(a)',
    sector: 'Healthcare',
    exposures: [
      { country: '(a)', percentage: 33.3, description: 'Revenue segment from 10-K' },
      { country: '(b)', percentage: 33.3, description: 'Revenue segment from 10-K' },
      { country: '(c)', percentage: 33.3, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-21',
    lastUpdated: '2025-12-10'
  },
  'NKE': {
    ticker: 'NKE',
    companyName: 'NKE Inc.',
    homeCountry: 'Sales through Direct to Consumer',
    sector: 'Consumer Cyclical',
    exposures: [
      { country: 'Sales through Direct to Consumer', percentage: 44.4, description: 'Revenue segment from 10-K' },
      { country: 'Apparel', percentage: 26.5, description: 'Revenue segment from 10-K' },
      { country: 'Europe, Middle East & Africa', percentage: 10.6, description: 'Revenue segment from 10-K' },
      { country: 'Asia Pacific & Latin America', percentage: 5.4, description: 'Revenue segment from 10-K' },
      { country: 'Equipment', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'China', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Hong Kong', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 1.9, description: 'Revenue segment from 10-K' },
      { country: '(Dollars in millions)', percentage: 1.7, description: 'Revenue segment from 10-K' },
      { country: 'Converse', percentage: 1.4, description: 'Revenue segment from 10-K' },
      { country: 'Corporate(3)', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Global Brand Divisions(2)', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-07-17',
    lastUpdated: '2025-12-10'
  },
  'AMD': {
    ticker: 'AMD',
    companyName: 'AMD Inc.',
    homeCountry: 'United States',
    sector: 'Technology',
    exposures: [
      { country: 'United States', percentage: 33.7, description: 'Revenue segment from 10-K' },
      { country: 'China (including Hong Kong)', percentage: 24.2, description: 'Revenue segment from 10-K' },
      { country: 'Singapore', percentage: 14, description: 'Revenue segment from 10-K' },
      { country: 'Taiwan', percentage: 12.8, description: 'Revenue segment from 10-K' },
      { country: 'Japan', percentage: 6.9, description: 'Revenue segment from 10-K' },
      { country: 'Other regions', percentage: 2.1, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 0.9, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-05',
    lastUpdated: '2025-12-10'
  },
  'BA': {
    ticker: 'BA',
    companyName: 'BA Inc.',
    homeCountry: 'United States',
    sector: 'Industrials',
    exposures: [
      { country: 'United States', percentage: 13.4, description: 'Revenue segment from 10-K' },
      { country: 'U.S. customers', percentage: 11.8, description: 'Revenue segment from 10-K' },
      { country: 'Commercial', percentage: 8.8, description: 'Revenue segment from 10-K' },
      { country: 'Asia', percentage: 8, description: 'Revenue segment from 10-K' },
      { country: 'Government', percentage: 5.9, description: 'Revenue segment from 10-K' },
      { country: 'Years ended December 31,', percentage: 4.9, description: 'Revenue segment from 10-K' },
      { country: 'Defense, Space & Security', percentage: 4.1, description: 'Revenue segment from 10-K' },
      { country: 'Commercial Airplanes', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Non-U.S. customers(1)', percentage: 3.4, description: 'Revenue segment from 10-K' },
      { country: 'Net loss attributable to Boeing common shareholders', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Net loss', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Net loss attributable to Boeing shareholders', percentage: 2, description: 'Revenue segment from 10-K' },
      { country: 'Loss from operations', percentage: 1.8, description: 'Revenue segment from 10-K' },
      { country: 'Other non-U.S.', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Reports of Independent Registered Public Accounting Firm', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Note 22 - Legal Proceedings', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 23 - Segment and Revenue Information', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 21 - Fair Value Measurements', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 20 - Derivative Financial Instruments', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 19 - Shareholders’ Equity', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 18 - Share-Based Compensation and Other Compensation Arrangements', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 17 - Postretirement Plans', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 15 - Arrangements with Off-Balance Sheet Risk', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 16 - Debt', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 14 - Liabilities, Commitments and Contingencies', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 12 - Investments', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 13 - Leases', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 11 - Property, Plant and Equipment', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 9 - Contracts with Customers', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 6 - Accounts Receivable', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 7 - Allowance for Losses on Financial Assets', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 8 - Inventories', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 4 - Earnings Per Share', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Israel', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Turkey', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 2 - Spirit Acquisition', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 3 - Goodwill and Acquired Intangibles', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 1 - Summary of Significant Accounting Policies', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Summary of Business Segment Data', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Oceania', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Estimated potential concessions and other considerations to 737 MAX customers, net of insurance recoveries', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Unallocated items, eliminations and other', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Canada', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Latin America, Caribbean and other', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Intersegment revenues eliminated on consolidation', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Africa', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'FAS/CAS service cost adjustment', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Revenue recognized on fixed-price contracts', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Revenue recognized at a point in time', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Intersegment revenues, eliminated on consolidation', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Revenue from the U.S. government(1)', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Revenue recognized over time', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Less: Mandatory convertible preferred stock dividends accumulated during the period', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Less: net loss attributable to noncontrolling interest', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-03',
    lastUpdated: '2025-12-10'
  },
  'GE': {
    ticker: 'GE',
    companyName: 'GE Inc.',
    homeCountry: 'Defense & Propulsion Technologies',
    sector: 'Industrials',
    exposures: [
      { country: 'Defense & Propulsion Technologies', percentage: 42.1, description: 'Revenue segment from 10-K' },
      { country: 'Years ended December 31', percentage: 5.8, description: 'Revenue segment from 10-K' },
      { country: 'Corporate & Other', percentage: 4.3, description: 'Revenue segment from 10-K' },
      { country: 'China region', percentage: 3.9, description: 'Revenue segment from 10-K' },
      { country: 'Asia (excluding China region)', percentage: 3.8, description: 'Revenue segment from 10-K' },
      { country: 'United Kingdom', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Germany', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'France', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Italy', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Spain', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Netherlands', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Switzerland', percentage: 1.2, description: 'Revenue segment from 10-K' },
      { country: 'Form 10-K Cross Reference Index', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Signatures', percentage: 1, description: 'Revenue segment from 10-K' },
      { country: 'Note 27   Quarterly Information', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Directors, Executive Officers and Corporate Governance', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Exhibits and Financial Statement Schedules', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 26   Summarized Financial Information', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 25   Segment and Geographic Information & Remaining Performance Obligation', percentage: 0.9, description: 'Revenue segment from 10-K' },
      { country: 'Note 23   Variable Interest Entities', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 20   Restructuring Charges and Separation Costs', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 21   Fair Value Measurements', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 22   Financial Instruments', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 17   Share-Based Compensation', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 18   Earnings Per Share Information', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 16   Shareholders' Equity', percentage: 0.8, description: 'Revenue segment from 10-K' },
      { country: 'Note 14   Sales Discounts and Allowances & All Other Liabilities', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 13   Postretirement Benefit Plans', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'United Arab Emirates', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Saudi Arabia', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'South Africa', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Israel', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Turkey', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Egypt', percentage: 0.7, description: 'Revenue segment from 10-K' },
      { country: 'Note 9   All Other Assets', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 10   Borrowings', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 11   Accounts Payable', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 12   Insurance Liabilities and Annuity Benefits', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 4   Current and Long-Term Receivables', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 5   Inventories, Including Deferred Inventory Costs', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 7   Goodwill and Other Intangible Assets', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 3   Investment Securities', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 2   Businesses Held for Sale and Discontinued Operations', percentage: 0.6, description: 'Revenue segment from 10-K' },
      { country: 'Note 1   Basis of Presentation and Summary of Significant Accounting Policies', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Statement of Financial Position', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Statement of Cash Flows', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Statement of Changes in Shareholders' Equity', percentage: 0.5, description: 'Revenue segment from 10-K' },
      { country: 'Audited Financial Statements and Notes', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Statement of Earnings (Loss)', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'United States', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Canada', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Mexico', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Brazil', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Argentina', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Chile', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Legal Proceedings', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Management and Auditor's Reports', percentage: 0.4, description: 'Revenue segment from 10-K' },
      { country: 'Cybersecurity', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Risk Factors', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Other Financial Data', percentage: 0.3, description: 'Revenue segment from 10-K' },
      { country: 'Non-GAAP Financial Measures', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Other Items', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Critical Accounting Estimates', percentage: 0.2, description: 'Revenue segment from 10-K' },
      { country: 'Capital Resources and Liquidity', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Management’s Discussion and Analysis of Financial Condition and Results of Operations (MD&A)', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'Segment Operations', percentage: 0.1, description: 'Revenue segment from 10-K' },
      { country: 'About GE Aerospace', percentage: 0, description: 'Revenue segment from 10-K' },
      { country: 'Forward-Looking Statements', percentage: 0, description: 'Revenue segment from 10-K' }
    ],
    dataSource: 'SEC 10-K 10-K filed 2025-02-03',
    lastUpdated: '2025-12-10'
  }
};